#!/bin/sh

choices='emoji\nmanpages\nbrightness\nvolume\nscreen shot\ntouchpad toggle\nlock\ncolorpick\nsuspend\nshutdown\nreboot'

choice=$(printf "$choices" | sort | dmenu -l 30)

PATH="$PATH:$HOME/.scripts"

case "$choice" in
    emoji) emojipick ;;
    colorpick) colorpick ;;
    manpages) manpdf ;;
    brightness) echo "" | dmenu -p "Input brightness: " | xargs -r xbacklight -set ;;
    volume) echo "" | dmenu -p "Input volume: " | xargs -r volume ;;
    'screen shot') flameshot gui ;;
    'touchpad toggle') touchpad_toggle ;;
    lock) slock ;;
    suspend) sudo systemctl suspend ;;
    shutdown) sudo systemctl poweroff ;;
    reboot) sudo systemctl reboot ;;
    *) notify-send invalid choice ;;
esac
