#!/bin/sh

choices="lock\nlogout\nsuspend\nshutdown\nreboot"

chosen=$(echo -e "$choices" | dmenu)

case "$chosen" in
    lock) slock ;;
    logout) pkill dwm ;;
    suspend) systemctl suspend ;;
    shutdown) shutdown now ;;
    reboot) reboot ;;
esac

